### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/opt/ml/input/data/train'

### ISSUE THREAD

**Issue by muchemwal** [slalom/dataops-infra#160]
I am getting the error above on ml-ops-on-aws training-endpoint. Can you assist with a resolution on this?

**Comment by aaronsteers** [comment]
I believe this is a bug in the ml-ops module. The original developer is no longer active on this repo but I would be happy for a PR if you have time to help debug. In general, the ML-Ops modules have not been terribly stable, to be fully honest. We merged #149 a little while back which slightly improved stability but this module may still require additional work before it's ready for production use cases.

**Comment by muchemwal** [comment]
Hi @aaronsteers I managed to get it working, I will push a PR when I finish my tests.

**Comment by aaronsteers** [comment]
@muchemwal - Awesome. I'll keep an eye out for your PR. Thanks!
